(function(){'use strict';var h=function(a,c,e){a=parseFloat(a.getAttribute(c));isFinite(a)||(a=e);return a};var l=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},r=function(a){if(l(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&l(a))return a;return null};var t=function(a,c,e){if(e){var f=document.createEvent("CustomEvent");f.initCustomEvent(a,!0,!0,e)}else f=document.createEvent("Event"),f.initEvent(a,!0,!0);c.dispatchEvent(f);return f};var u=function(a){a=1-a;return 1-a*a*a};var v=/[^\d]+$/,w=function(a,c,e,f){if(!a.hasAttribute(c))return e;a=a.getAttribute(c);isNaN(parseFloat(a))?f=e:(e=parseFloat(a),(a=(a=a.match(v))&&a[0]||null)&&(a=a.trim()),c=e,"%"==a&&(c=Number((e/100*f).toFixed(2))),f=c);return f};var y=function(a,c,e){var f=w(a,"xenter",0,c),d=a.hasAttribute("xmiddle")?w(a,"xmiddle",0,c):void 0,b=w(a,"xexit",0,c),g=w(a,"yenter",0,e),k=a.hasAttribute("ymiddle")?w(a,"ymiddle",0,e):void 0,m=w(a,"yexit",0,e),n=x(a,"opacityenter"),p=x(a,"opacitymiddle"),z=x(a,"opacityexit"),A=a.hasAttribute("fixed"),G=a.getAttribute("assettype")||"",H=a.getAttribute("source")||"",I=a.getAttribute("easing")||"linear";c=w(a,"width",c,c);e=w(a,"height",e,e);var J=a.hasAttribute("yawenter")?parseInt(a.getAttribute("yawenter"),
10):void 0,K=a.hasAttribute("yawmiddle")?parseInt(a.getAttribute("yawmiddle"),10):void 0,L=a.hasAttribute("yawexit")?parseInt(a.getAttribute("yawexit"),10):void 0,M=a.getAttribute("exit-url")||void 0,q=[];q.push({opacity:n,x:f,y:g,h:J});void 0!==d&&void 0!==k&&q.push({opacity:p,x:d,y:k,h:K});q.push({opacity:z,x:b,y:m,h:L});return{F:G,a:q,easing:I,element:a,u:M,fixed:A,height:e,source:H,width:c}},B=function(a,c,e,f,d,b){d=void 0===d?0:d;b=void 0===b?1:b;if(f<=d)return a;if(f>=b)return c;switch(e){case "ease-in":e=
f*f*f;d*=d*d;b*=b*b;break;case "ease-in-out":e=3*f*f-2*f*f*f;d=3*d*d-2*d*d*d;b=3*b*b-2*b*b*b;break;case "ease-out":e=u(f);d=u(d);b=u(b);break;default:e=f}return 1/(b-d)*(c-a)*(e-d)+a},x=function(a,c){if(!a.hasAttribute(c))return 1;a=a.getAttribute(c);a=parseFloat(a);return isNaN(a)?1:0>a?0:1<a?1:a};var C=function(a,c){function e(){}e.prototype=c.prototype;a.K=c.prototype;a.prototype=new e;a.prototype.constructor=a};var D=function(){};C(D,HTMLElement);D.prototype.createdCallback=function(){this.m=[];this.i=this.B=null;this.f=[0,1];this.c=[];this.o=this.G.bind(this);this.C=this.s=!1;this.D=this.J.bind(this);this.A=0;this.w=this.I.bind(this);this.v=this.H.bind(this);this.j=null};
D.prototype.attachedCallback=function(){this.ownerDocument.addEventListener("hostpagescroll",this.D);window.Enabler&&(Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this.w),Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this.v));if("function"==typeof this.gwdLoad&&"function"==typeof this.gwdIsLoaded&&!this.gwdIsLoaded()){var a=r(this),c=a&&"function"==typeof a.gwdIsLoaded;(!a||c&&a.gwdIsLoaded())&&this.gwdLoad()}};
D.prototype.detachedCallback=function(){this.ownerDocument.removeEventListener("hostpagescroll",this.D);window.Enabler&&(Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this.w),Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this.v));this.removeEventListener("ready",this.o,!1)};
D.prototype.gwdLoad=function(){if(!this.gwdIsLoaded()){this.c.length=0;this.initializeParallax(!0);for(var a=this.c.length-1;0<=a;a--)this.c[a].gwdLoad();this.c=this.c.filter(function(c){return!c.gwdIsLoaded()});0==this.c.length?E(this):this.addEventListener("ready",this.o,!1)}};D.prototype.gwdIsLoaded=function(){return this.s&&0==this.c.length};D.prototype.G=function(a){a=this.c.indexOf(a.target);0<=a&&(this.c.splice(a,1),0==this.c.length&&(E(this),this.removeEventListener("ready",this.o,!1)))};
var E=function(a){a.C||t("ready",a);a.C=!0;a.j&&(F(a,a.j.creativeFramePercentY,a.j.windowHeight+a.i),a.j=null)};
D.prototype.initializeParallax=function(a){var c=this;this.style.overflow="hidden";this.m.length=0;this.B=this.clientWidth;this.i=this.clientHeight;this.f=N(this);for(var e=this.ownerDocument,f={},d=0;d<this.children.length;f={l:f.l},d++)if(!this.children[d].hasAttribute("data-gwd-csd-ghost-id")){var b=y(this.children[d],this.B,this.i);this.m.push(b);b.element.style.position="absolute";b.element.style.left="0px";b.element.style.top="0px";b.element.style.width=b.width+"px";b.element.style.height=b.height+
"px";b.element.style.transform="translate("+b.a[0].x+"px, "+b.a[0].y+"px)";b.element.style.opacity=b.a[0].opacity+"";void 0!=b.a[0].h&&b.element.setTargetYaw(b.a[0].h);if(a){if("image"==b.F&&b.source){for(;b.element.firstChild;)b.element.removeChild(b.element.firstChild);var g=e.createElement("gwd-image");g.style.width="100%";g.style.height="100%";g.setAttribute("source",b.source);this.c.push(g);b.element.appendChild(g)}else b.element.gwdLoad&&this.c.push(b.element);b.u&&(f.l=b.u,b.element.addEventListener("click",
function(k){return function(){t("layerclickexit",c,{url:k.l}).detail.handled||window.open(k.l)}}(f)))}}this.s=!0};D.prototype.J=function(a){a=a.detail;this.A=a.creativeFramePercentY;this.gwdIsLoaded()?F(this,a.creativeFramePercentY,a.windowHeight+this.i):this.j=a};
var F=function(a,c,e){for(var f=0;f<a.m.length;f++){var d=a.m[f],b=void 0,g=void 0;b=d.a.length-1;var k=a.f[0],m=a.f[a.f.length-1],n=d.a[0],p=d.a[d.a.length-1];if(d.a.length===a.f.length)for(g=0;g<b;g++)if(a.f[g]<=c&&c<=a.f[g+1]){k=a.f[g];m=a.f[g+1];n=d.a[g];p=d.a[g+1];break}d.fixed?(b=d.a[0].x,g=d.a[0].y+c*e):(b=B(n.x,p.x,d.easing,c,k,m),g=B(n.y,p.y,d.easing,c,k,m));var z=B(n.opacity,p.opacity,d.easing,c,k,m);d.element.style.transform="translate("+b+"px, "+g+"px)";d.element.style.opacity=z+"";d.a.some(function(A){return void 0===
A.h})||d.element.setTargetYaw(Math.round(B(n.h,p.h,d.easing,c,k,m)))}t("parallaxscrolled",a,{yscroll:c})},N=function(a){var c=h(a,"start",0),e=h(a,"end",1);if(0>c||1<c||0>e||1<e||c>=e)c=0,e=1;a=h(a,"middle",-1);return a>=c&&a<=e?[c,a,e]:[c,e]};D.prototype.I=function(){var a=this;setTimeout(function(){a.initializeParallax(!1);F(a,1,window.innerHeight+a.i)},0)};D.prototype.H=function(){var a=this;setTimeout(function(){a.initializeParallax(!1);F(a,a.A,window.innerHeight+a.i)},0)};var O=function(){};C(O,D);O.prototype.createdCallback=function(){O.K.createdCallback.call(this)};document.registerElement("gwd-parallax",{prototype:O.prototype});}).call(this);
