(function(){'use strict';var e=function(a,b){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=1);return a},p=function(a,b,c){a=m(a,b,c);return 0<a?a:c},m=function(a,b,c){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=c);return a},q=function(a,b,c){return a.hasAttribute(b)?a.getAttribute(b):c};var t=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},w=function(a){if(t(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&t(a))return a;return null},x=function(a,b,c,d){d=d||b;a.hasAttribute(b)?(a=a.getAttribute(b),c.setAttribute(d,a)):c.removeAttribute(d)},y=function(a,b){var c=[];if(a=q(a,b,""))for(a=a.split(","),b=0;b<a.length;b++)c[b]=a[b].trim();return c};var z="gwd-blinds gwd-door-wipe gwd-fade gwd-iris-wipe gwd-push gwd-radial-wipe gwd-rotate gwd-slice gwd-split-push gwd-stripe-wipe gwd-venetian-blinds gwd-wipe gwd-zigzag".split(" ");var B=function(a,b,c){if(c){var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c)}else d=document.createEvent("Event"),d.initEvent(a,!0,!0);b.dispatchEvent(d);return d};var C=function(a,b,c,d){var f=new XMLHttpRequest;f.open("GET",b);f.setRequestHeader("Content-Type","image/svg+xml");f.addEventListener("load",function(g){g=g.target.responseText;if(g=(new DOMParser).parseFromString(g,"image/svg+xml").getElementsByTagName("svg")[0])if(g.hasAttribute("width")&&g.hasAttribute("height"))a.src=b;else{var n=c,l=d,h=g.getAttribute("viewBox");if(h){var k=h.match(/[\d,\.]+ [\d,\.]+ ([\d,\.]+) ([\d,\.]+)/);k&&(h=k[1],k=k[2],h&&k&&(l=Math.min(c/h,d/k),n=h*l,l*=k))}g.setAttribute("width",
n);g.setAttribute("height",l);g=(new XMLSerializer).serializeToString(g);a.src="data:image/svg+xml;base64,"+window.btoa(g)}});f.send()};var D=function(){};goog.inherits(D,HTMLElement);
D.prototype.createdCallback=function(){this.o=[];this.l=[];this.C=this.ba.bind(this);this.w=!1;this.T=0;Object.defineProperty(this,"frameCount",{enumerable:!0,get:function(){return this.l.length}});Object.defineProperty(this,"currentIndex",{enumerable:!0,get:function(){return 0<this.frameCount?this.a+1:void 0}});this.G=this.i=this.Y=null;this.j=this.J=0;this.A=this.B=!1;this.h=null;this.U=this.ca.bind(this);this.X=this.fa.bind(this);this.W=this.ea.bind(this);this.V=this.da.bind(this);this.g=this.I=
!1;this.u=null};
D.prototype.attachedCallback=function(){this.f=this.firstElementChild&&-1!==z.indexOf(this.firstElementChild.tagName.toLowerCase())?this.firstElementChild:null;this.c=this.clientWidth;this.b=this.clientHeight;var a=m(this,"swipe-committed-threshold",.25);this.ia=a*this.c;this.ja=a*this.b;this.ka=m(this,"swipe-threshold",.3);if(this.ga=this.hasAttribute("has-navigation"))this.b-=36,this.h=document.createElement("gwd-gallerynavigation"),this.h.setAttribute("for",this.id),this.appendChild(this.h),x(this,
"navigation-highlight",this.h,"highlight"),x(this,"navigation-thumbnails",this.h,"use-thumbnails");this.u||(a=document.createElement("canvas"),this.appendChild(a),this.u=a,E(this,this.u));this.O=this.u.getBoundingClientRect();this.P=this.u.getContext("2d");this.D=y(this,"images");this.H=e(this,"start-frame");this.M=1E3*p(this,"transition-duration",1);this.aa=this.hasAttribute("autoplay");this.$=1E3*p(this,"autoplay-frame-interval",1.5);this.N=e(this,"autoplay-loop-count");this.Z=this.hasAttribute("wrap");
this.F=q(this,"scaling","stretch");this.R=q(this,"easing","linear");this.m=document.createElement("gwd-gesture");this.appendChild(this.m);this.v=q(this,"gesture","click");this.K=this.hasAttribute("enable-interactive-transition");a=this.m;a.addEventListener("tap",this.U,!1);if("swipe"==this.v||"click"==this.v&&this.K)a.addEventListener("trackstart",this.X,!1),a.addEventListener("track",this.W,!1),a.addEventListener("trackend",this.V,!1);this.ha=this.hasAttribute("ignore-reverse-swipe");this.S=y(this,
"exit-urls");if("function"==typeof this.gwdLoad&&"function"==typeof this.gwdIsLoaded&&!this.gwdIsLoaded()){var b=(a=w(this))&&"function"==typeof a.gwdIsLoaded;(!a||b&&a.gwdIsLoaded())&&this.gwdLoad()}};
D.prototype.detachedCallback=function(){var a=this.m;a.removeEventListener("tap",this.U,!1);if("swipe"==this.v||"click"==this.v&&this.K)a.removeEventListener("trackstart",this.X,!1),a.removeEventListener("track",this.W,!1),a.removeEventListener("trackend",this.V,!1);this.m.parentNode&&this.m.parentNode.removeChild(this.m);this.h&&(this.removeChild(this.h),this.h=null)};
D.prototype.attributeChangedCallback=function(a){if(this.w)switch(a){case "transition-duration":this.M=1E3*p(this,"transition-duration",1);break;case "easing":this.R=q(this,"easing","linear");break;case "scaling":this.F=q(this,"scaling","stretch");F(this);G(this,this.a,!1);break;case "exit-urls":this.S=y(this,"exit-urls")}};
D.prototype.gwdLoad=function(){if(!this.w)if(this.T=0,this.D.length)for(var a=0;a<this.D.length;a++){var b=document.createElement("img");b.addEventListener("load",this.C,!1);b.addEventListener("error",this.C,!1);var c=this.D[a];"svg"==c.split(".").pop().toLowerCase()?C(b,c,this.c,this.b):b.src=c;this.o.push(b)}else this.w=!0,B("ready",this)};D.prototype.gwdIsLoaded=function(){return this.w};
var E=function(a,b){var c=window.devicePixelRatio;b.width=a.c*c;b.height=a.b*c;b.style.width=a.c+"px";b.style.height=a.b+"px";b.getContext("2d").scale(c,c)};D.prototype.ba=function(a){var b=a.target;b.removeEventListener("load",this.C,!1);b.removeEventListener("error",this.C,!1);b=this.o.indexOf(b);0<=b&&("error"==a.type&&this.o.splice(b,1),++this.T==this.D.length&&(F(this),this.aa?this.startAutoplay():this.goToFrame(this.H,!1),this.w=!0,B("ready",this)))};
D.prototype.getFrame=function(a){if(0!=this.frameCount)return this.o[a-1]};D.prototype.goToFrame=function(a,b){this.stop(!1);this.frameCount&&(a=H(this,a),a!=this.a&&G(this,a,b))};
var G=function(a,b,c){B("frameactivated",a,{id:b+1});void 0==c&&(c=!!a.f);c?(a.s=b,a.Y=Date.now()-(a.g?a.j*a.M:0),a.g=!1,a.L()):(a.P.clearRect(0,0,a.c,a.b),a.P.drawImage(a.l[b],0,0,a.c,a.b),I(a,b))},F=function(a){a.l=[];for(var b=0;b<a.o.length;b++){var c=a.o[b],d=c.naturalWidth,f=c.naturalHeight,g=!1;d&&f||(a.appendChild(c),g=!0,d=c.width,f=c.height);var n=0,l=0,h=d,k=f,r=0,A=0,u=a.c,v=a.b;"contain"==a.F?(r=Math.min(a.c/d,a.b/f),u=r*d,v=r*f,r=(a.c-u)/2,A=(a.b-v)/2):"cover"==a.F?(n=Math.max(a.c/d,
a.b/f),h=a.c/n,k=a.b/n,n=(d-h)/2,l=(f-k)/2):"none"==a.F&&(l=d-a.c,h=f-a.b,n=Math.max(l/2,0),r=Math.max(-l/2,0),l=Math.max(h/2,0),A=Math.max(-h/2,0),h=Math.min(d,a.c),k=Math.min(f,a.b),u=h,v=k);d=document.createElement("canvas");E(a,d);d.getContext("2d").drawImage(c,n,l,h,k,r,A,u,v);a.l.push(d);g&&a.removeChild(c)}},I=function(a,b){a.a!=b&&(a.a=b,B("frameshown",a,{frameIndex:a.a}),0==a.a?B("reachleftend",a):a.a==a.frameCount-1&&B("reachrightend",a))};
D.prototype.goForwards=function(){this.stop(!1);(this.Z||this.a!=this.frameCount-1)&&this.frameCount&&G(this,J(this,!0))};D.prototype.goBackwards=function(){this.stop(!1);(this.Z||0!=this.a)&&this.frameCount&&G(this,J(this,!1))};var J=function(a,b){return((b?a.a+1:a.a-1)+a.frameCount)%a.frameCount},H=function(a,b){1>b?b=1:b>a.frameCount&&(b=a.frameCount);return b-1};
D.prototype.L=function(){this.g||(this.j=K(this,Math.min(1,(Date.now()-this.Y)/this.M)),this.i=requestAnimationFrame(this.L.bind(this)));this.f.renderAnimation(this.l[this.a],this.l[this.s],this.j);1!=this.j||this.g||(this.i&&(cancelAnimationFrame(this.i),this.i=null),this.f.resetDirection(),I(this,this.s),(this.A||this.B)&&L(this))};var K=function(a,b){switch(a.R){case "ease-in":return b*b*b;case "ease-in-out":return 3*b*b-2*b*b*b;case "ease-out":return a=1-b,1-a*a*a;default:return b}};
D.prototype.startAutoplay=function(a){this.J=0;a||this.goToFrame(this.H,!1);this.A=!0;L(this)};D.prototype.rotateOnce=function(a){a||this.goToFrame(this.H,!1);this.B=!0;L(this)};var M=function(a){var b=H(a,a.H);return 0==b?a.frameCount:b};D.prototype.updateAnimationElement=function(a){this.f=a};
var L=function(a){if(a.B){if(a.a==M(a)-1){a.stop(!0);return}}else if(a.A&&0!=a.N&&(a.a==M(a)-1&&a.J++,a.J>=a.N)){a.stop(!0);return}a.G=setTimeout(function(){requestAnimationFrame(function(){a.frameCount&&G(a,J(a,!0));a.f||L(a)})},a.$)},N=function(a){.5<=a.j?G(a,a.s,!1):G(a,a.a,!1)};
D.prototype.stop=function(a,b){b=null!=b?b:!0;this.i&&(cancelAnimationFrame(this.i),this.i=null,N(this));this.g&&(this.g=!1,N(this),this.f.resetDirection());this.G&&(clearTimeout(this.G),this.G=null);this.B?(this.B=!1,b&&B("rotateonceended",this,{completed:!!a})):this.A&&(this.A=!1,b&&B("autoplayended",this,{completed:!!a}))};
D.prototype.ca=function(){if(this.frameCount){B("frametap",this,{id:this.a+1});var a=this.S[this.a];a?(this.stop(!1),B("frameexit",this,{url:a}).detail.handled||window.open(a)):"click"==this.v&&this.goForwards()}};D.prototype.fa=function(){this.stop(!1)};
D.prototype.ea=function(a){var b=this;if(!this.I)if(this.K&&O(this,a.dx,a.dy,!1)){this.g||(this.g=!0,P(this,a.dx,a.dy,function(){b.s=J(b,!0)},function(){b.s=J(b,!1)}));a=Math.abs(a.dy)>Math.abs(a.dx)?(a.clientY-this.O.top)/this.b:(a.clientX-this.O.left)/this.c;var c=this.f.getSupportedSwipeDirection();0>c[0]+c[1]&&(a=1-a);this.j=a;this.L()}else O(this,a.dx,a.dy,!0)&&(this.I=!0,P(this,a.dx,a.dy,this.goForwards.bind(this),this.goBackwards.bind(this)))};
D.prototype.da=function(a){this.I?this.I=!1:this.g?this.j>=this.ka?G(this,this.s):this.stop(!1,!1):O(this,a.dx,a.dy,!1)&&P(this,a.dx,a.dy,this.goForwards.bind(this),this.goBackwards.bind(this))};
var O=function(a,b,c,d){var f=Math.abs(c)>Math.abs(b),g=a.f?a.f.getSupportedSwipeDirection():[0,0];b*=g[0];c*=g[1];return(f?c:b)?a.ha&&(f?0>c:0>b)?!1:d?f?Math.abs(c)>=a.ja:Math.abs(b)>=a.ia:!0:!1},P=function(a,b,c,d,f){Math.abs(c)>Math.abs(b)?0<c?(a.f.setDirection("toptobottom"),f()):(a.f.setDirection("bottomtotop"),d()):0<b?(a.f.setDirection("lefttoright"),f()):(a.f.setDirection("righttoleft"),d())};document.registerElement("gwd-transitiongallery",{prototype:D.prototype});}).call(this);
